### ISSUE TITLE
Please update update.sh for v5.12

### ISSUE THREAD

**Issue by CartoonFan** [YellowOnion/bcachefs-patches#1]
Hello there! It seems that bcachefs was recently rebased for the 5.12 kernel, so maybe it's time for a script update? I'd try to help but I don't really understand the "oldest" dates in the script. Additionally, the bcachefs submodule doesn't have commit a5c0e1bb306e79b40b2432a22f164697c8b22110 anymore, so I don't know how to check out the submodule (besides just deleting it and checking it out myself). Thanks!

**Comment by YellowOnion** [comment]
hey sorry I didn't see this until just now, I'm investigating it now.

The dates are there just to stop it creating patches that are "behind" the first commit, I ended up with a bunch of unworkable, 10MB patches doing who knows what.
